#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DizitalBazarDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_MainCategory(tbl_MainCategory instance);
  partial void Updatetbl_MainCategory(tbl_MainCategory instance);
  partial void Deletetbl_MainCategory(tbl_MainCategory instance);
  partial void Inserttbl_SubCategory(tbl_SubCategory instance);
  partial void Updatetbl_SubCategory(tbl_SubCategory instance);
  partial void Deletetbl_SubCategory(tbl_SubCategory instance);
  partial void Inserttbl_Product(tbl_Product instance);
  partial void Updatetbl_Product(tbl_Product instance);
  partial void Deletetbl_Product(tbl_Product instance);
  partial void Inserttbl_ShoppingCart(tbl_ShoppingCart instance);
  partial void Updatetbl_ShoppingCart(tbl_ShoppingCart instance);
  partial void Deletetbl_ShoppingCart(tbl_ShoppingCart instance);
  partial void Inserttbl_UserProfile(tbl_UserProfile instance);
  partial void Updatetbl_UserProfile(tbl_UserProfile instance);
  partial void Deletetbl_UserProfile(tbl_UserProfile instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DigitalBazarConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_MainCategory> tbl_MainCategories
	{
		get
		{
			return this.GetTable<tbl_MainCategory>();
		}
	}
	
	public System.Data.Linq.Table<tbl_SubCategory> tbl_SubCategories
	{
		get
		{
			return this.GetTable<tbl_SubCategory>();
		}
	}
	
	public System.Data.Linq.Table<tbl_Product> tbl_Products
	{
		get
		{
			return this.GetTable<tbl_Product>();
		}
	}
	
	public System.Data.Linq.Table<tbl_ShoppingCart> tbl_ShoppingCarts
	{
		get
		{
			return this.GetTable<tbl_ShoppingCart>();
		}
	}
	
	public System.Data.Linq.Table<tbl_UserProfile> tbl_UserProfiles
	{
		get
		{
			return this.GetTable<tbl_UserProfile>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.showProduct")]
	public ISingleResult<showProductResult> showProduct()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<showProductResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.product_list")]
	public ISingleResult<product_listResult> product_list([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pcat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string scat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pcat, scat, choice);
		return ((ISingleResult<product_listResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Shop_Cart_View")]
	public ISingleResult<Shop_Cart_ViewResult> Shop_Cart_View([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string sessionId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> choice)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionId, choice);
		return ((ISingleResult<Shop_Cart_ViewResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_MainCategory")]
public partial class tbl_MainCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Catname;
	
	private string _desc;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private EntitySet<tbl_SubCategory> _tbl_SubCategories;
	
	private EntitySet<tbl_Product> _tbl_Products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCatnameChanging(string value);
    partial void OnCatnameChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OndateonChanging(System.Nullable<System.DateTime> value);
    partial void OndateonChanged();
    #endregion
	
	public tbl_MainCategory()
	{
		this._tbl_SubCategories = new EntitySet<tbl_SubCategory>(new Action<tbl_SubCategory>(this.attach_tbl_SubCategories), new Action<tbl_SubCategory>(this.detach_tbl_SubCategories));
		this._tbl_Products = new EntitySet<tbl_Product>(new Action<tbl_Product>(this.attach_tbl_Products), new Action<tbl_Product>(this.detach_tbl_Products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catname", DbType="VarChar(50)")]
	public string Catname
	{
		get
		{
			return this._Catname;
		}
		set
		{
			if ((this._Catname != value))
			{
				this.OnCatnameChanging(value);
				this.SendPropertyChanging();
				this._Catname = value;
				this.SendPropertyChanged("Catname");
				this.OnCatnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(50)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this.OndescChanging(value);
				this.SendPropertyChanging();
				this._desc = value;
				this.SendPropertyChanged("desc");
				this.OndescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this.OndateonChanging(value);
				this.SendPropertyChanging();
				this._dateon = value;
				this.SendPropertyChanged("dateon");
				this.OndateonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MainCategory_tbl_SubCategory", Storage="_tbl_SubCategories", ThisKey="Id", OtherKey="pid")]
	public EntitySet<tbl_SubCategory> tbl_SubCategories
	{
		get
		{
			return this._tbl_SubCategories;
		}
		set
		{
			this._tbl_SubCategories.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MainCategory_tbl_Product", Storage="_tbl_Products", ThisKey="Id", OtherKey="pid")]
	public EntitySet<tbl_Product> tbl_Products
	{
		get
		{
			return this._tbl_Products;
		}
		set
		{
			this._tbl_Products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_SubCategories(tbl_SubCategory entity)
	{
		this.SendPropertyChanging();
		entity.tbl_MainCategory = this;
	}
	
	private void detach_tbl_SubCategories(tbl_SubCategory entity)
	{
		this.SendPropertyChanging();
		entity.tbl_MainCategory = null;
	}
	
	private void attach_tbl_Products(tbl_Product entity)
	{
		this.SendPropertyChanging();
		entity.tbl_MainCategory = this;
	}
	
	private void detach_tbl_Products(tbl_Product entity)
	{
		this.SendPropertyChanging();
		entity.tbl_MainCategory = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SubCategory")]
public partial class tbl_SubCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Scatname;
	
	private string _desc;
	
	private System.Nullable<int> _pid;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private EntitySet<tbl_Product> _tbl_Products;
	
	private EntityRef<tbl_MainCategory> _tbl_MainCategory;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnScatnameChanging(string value);
    partial void OnScatnameChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnpidChanging(System.Nullable<int> value);
    partial void OnpidChanged();
    partial void OndateonChanging(System.Nullable<System.DateTime> value);
    partial void OndateonChanged();
    #endregion
	
	public tbl_SubCategory()
	{
		this._tbl_Products = new EntitySet<tbl_Product>(new Action<tbl_Product>(this.attach_tbl_Products), new Action<tbl_Product>(this.detach_tbl_Products));
		this._tbl_MainCategory = default(EntityRef<tbl_MainCategory>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scatname", DbType="VarChar(50)")]
	public string Scatname
	{
		get
		{
			return this._Scatname;
		}
		set
		{
			if ((this._Scatname != value))
			{
				this.OnScatnameChanging(value);
				this.SendPropertyChanging();
				this._Scatname = value;
				this.SendPropertyChanged("Scatname");
				this.OnScatnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(50)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this.OndescChanging(value);
				this.SendPropertyChanging();
				this._desc = value;
				this.SendPropertyChanged("desc");
				this.OndescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
	public System.Nullable<int> pid
	{
		get
		{
			return this._pid;
		}
		set
		{
			if ((this._pid != value))
			{
				if (this._tbl_MainCategory.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpidChanging(value);
				this.SendPropertyChanging();
				this._pid = value;
				this.SendPropertyChanged("pid");
				this.OnpidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this.OndateonChanging(value);
				this.SendPropertyChanging();
				this._dateon = value;
				this.SendPropertyChanged("dateon");
				this.OndateonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SubCategory_tbl_Product", Storage="_tbl_Products", ThisKey="Id", OtherKey="sid")]
	public EntitySet<tbl_Product> tbl_Products
	{
		get
		{
			return this._tbl_Products;
		}
		set
		{
			this._tbl_Products.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MainCategory_tbl_SubCategory", Storage="_tbl_MainCategory", ThisKey="pid", OtherKey="Id", IsForeignKey=true)]
	public tbl_MainCategory tbl_MainCategory
	{
		get
		{
			return this._tbl_MainCategory.Entity;
		}
		set
		{
			tbl_MainCategory previousValue = this._tbl_MainCategory.Entity;
			if (((previousValue != value) 
						|| (this._tbl_MainCategory.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_MainCategory.Entity = null;
					previousValue.tbl_SubCategories.Remove(this);
				}
				this._tbl_MainCategory.Entity = value;
				if ((value != null))
				{
					value.tbl_SubCategories.Add(this);
					this._pid = value.Id;
				}
				else
				{
					this._pid = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_MainCategory");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_Products(tbl_Product entity)
	{
		this.SendPropertyChanging();
		entity.tbl_SubCategory = this;
	}
	
	private void detach_tbl_Products(tbl_Product entity)
	{
		this.SendPropertyChanging();
		entity.tbl_SubCategory = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Product")]
public partial class tbl_Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _pname;
	
	private string _desc;
	
	private System.Nullable<decimal> _price;
	
	private System.Nullable<int> _qty;
	
	private string _size;
	
	private string _color;
	
	private string _material;
	
	private string _imgthumb;
	
	private string _imgfront;
	
	private string _imgback;
	
	private System.Nullable<int> _pid;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private EntitySet<tbl_ShoppingCart> _tbl_ShoppingCarts;
	
	private EntityRef<tbl_MainCategory> _tbl_MainCategory;
	
	private EntityRef<tbl_SubCategory> _tbl_SubCategory;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnpnameChanging(string value);
    partial void OnpnameChanged();
    partial void OndescChanging(string value);
    partial void OndescChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnqtyChanging(System.Nullable<int> value);
    partial void OnqtyChanged();
    partial void OnsizeChanging(string value);
    partial void OnsizeChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OnmaterialChanging(string value);
    partial void OnmaterialChanged();
    partial void OnimgthumbChanging(string value);
    partial void OnimgthumbChanged();
    partial void OnimgfrontChanging(string value);
    partial void OnimgfrontChanged();
    partial void OnimgbackChanging(string value);
    partial void OnimgbackChanged();
    partial void OnpidChanging(System.Nullable<int> value);
    partial void OnpidChanged();
    partial void OnsidChanging(System.Nullable<int> value);
    partial void OnsidChanged();
    partial void OndateonChanging(System.Nullable<System.DateTime> value);
    partial void OndateonChanged();
    #endregion
	
	public tbl_Product()
	{
		this._tbl_ShoppingCarts = new EntitySet<tbl_ShoppingCart>(new Action<tbl_ShoppingCart>(this.attach_tbl_ShoppingCarts), new Action<tbl_ShoppingCart>(this.detach_tbl_ShoppingCarts));
		this._tbl_MainCategory = default(EntityRef<tbl_MainCategory>);
		this._tbl_SubCategory = default(EntityRef<tbl_SubCategory>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="VarChar(50)")]
	public string pname
	{
		get
		{
			return this._pname;
		}
		set
		{
			if ((this._pname != value))
			{
				this.OnpnameChanging(value);
				this.SendPropertyChanging();
				this._pname = value;
				this.SendPropertyChanged("pname");
				this.OnpnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(150)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this.OndescChanging(value);
				this.SendPropertyChanging();
				this._desc = value;
				this.SendPropertyChanged("desc");
				this.OndescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
	public System.Nullable<int> qty
	{
		get
		{
			return this._qty;
		}
		set
		{
			if ((this._qty != value))
			{
				this.OnqtyChanging(value);
				this.SendPropertyChanging();
				this._qty = value;
				this.SendPropertyChanged("qty");
				this.OnqtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(50)")]
	public string size
	{
		get
		{
			return this._size;
		}
		set
		{
			if ((this._size != value))
			{
				this.OnsizeChanging(value);
				this.SendPropertyChanging();
				this._size = value;
				this.SendPropertyChanged("size");
				this.OnsizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this.OncolorChanging(value);
				this.SendPropertyChanging();
				this._color = value;
				this.SendPropertyChanged("color");
				this.OncolorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="VarChar(50)")]
	public string material
	{
		get
		{
			return this._material;
		}
		set
		{
			if ((this._material != value))
			{
				this.OnmaterialChanging(value);
				this.SendPropertyChanging();
				this._material = value;
				this.SendPropertyChanged("material");
				this.OnmaterialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgthumb", DbType="VarChar(50)")]
	public string imgthumb
	{
		get
		{
			return this._imgthumb;
		}
		set
		{
			if ((this._imgthumb != value))
			{
				this.OnimgthumbChanging(value);
				this.SendPropertyChanging();
				this._imgthumb = value;
				this.SendPropertyChanged("imgthumb");
				this.OnimgthumbChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgfront", DbType="VarChar(50)")]
	public string imgfront
	{
		get
		{
			return this._imgfront;
		}
		set
		{
			if ((this._imgfront != value))
			{
				this.OnimgfrontChanging(value);
				this.SendPropertyChanging();
				this._imgfront = value;
				this.SendPropertyChanged("imgfront");
				this.OnimgfrontChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgback", DbType="VarChar(50)")]
	public string imgback
	{
		get
		{
			return this._imgback;
		}
		set
		{
			if ((this._imgback != value))
			{
				this.OnimgbackChanging(value);
				this.SendPropertyChanging();
				this._imgback = value;
				this.SendPropertyChanged("imgback");
				this.OnimgbackChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
	public System.Nullable<int> pid
	{
		get
		{
			return this._pid;
		}
		set
		{
			if ((this._pid != value))
			{
				if (this._tbl_MainCategory.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpidChanging(value);
				this.SendPropertyChanging();
				this._pid = value;
				this.SendPropertyChanged("pid");
				this.OnpidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				if (this._tbl_SubCategory.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnsidChanging(value);
				this.SendPropertyChanging();
				this._sid = value;
				this.SendPropertyChanged("sid");
				this.OnsidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this.OndateonChanging(value);
				this.SendPropertyChanging();
				this._dateon = value;
				this.SendPropertyChanged("dateon");
				this.OndateonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Product_tbl_ShoppingCart", Storage="_tbl_ShoppingCarts", ThisKey="Id", OtherKey="ProductID")]
	public EntitySet<tbl_ShoppingCart> tbl_ShoppingCarts
	{
		get
		{
			return this._tbl_ShoppingCarts;
		}
		set
		{
			this._tbl_ShoppingCarts.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_MainCategory_tbl_Product", Storage="_tbl_MainCategory", ThisKey="pid", OtherKey="Id", IsForeignKey=true)]
	public tbl_MainCategory tbl_MainCategory
	{
		get
		{
			return this._tbl_MainCategory.Entity;
		}
		set
		{
			tbl_MainCategory previousValue = this._tbl_MainCategory.Entity;
			if (((previousValue != value) 
						|| (this._tbl_MainCategory.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_MainCategory.Entity = null;
					previousValue.tbl_Products.Remove(this);
				}
				this._tbl_MainCategory.Entity = value;
				if ((value != null))
				{
					value.tbl_Products.Add(this);
					this._pid = value.Id;
				}
				else
				{
					this._pid = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_MainCategory");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SubCategory_tbl_Product", Storage="_tbl_SubCategory", ThisKey="sid", OtherKey="Id", IsForeignKey=true)]
	public tbl_SubCategory tbl_SubCategory
	{
		get
		{
			return this._tbl_SubCategory.Entity;
		}
		set
		{
			tbl_SubCategory previousValue = this._tbl_SubCategory.Entity;
			if (((previousValue != value) 
						|| (this._tbl_SubCategory.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_SubCategory.Entity = null;
					previousValue.tbl_Products.Remove(this);
				}
				this._tbl_SubCategory.Entity = value;
				if ((value != null))
				{
					value.tbl_Products.Add(this);
					this._sid = value.Id;
				}
				else
				{
					this._sid = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_SubCategory");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_ShoppingCarts(tbl_ShoppingCart entity)
	{
		this.SendPropertyChanging();
		entity.tbl_Product = this;
	}
	
	private void detach_tbl_ShoppingCarts(tbl_ShoppingCart entity)
	{
		this.SendPropertyChanging();
		entity.tbl_Product = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ShoppingCart")]
public partial class tbl_ShoppingCart : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CartID;
	
	private System.Nullable<int> _ProductID;
	
	private System.Nullable<int> _Quantity;
	
	private string _SessionID;
	
	private System.Nullable<decimal> _Price;
	
	private System.Nullable<System.DateTime> _DateAdded;
	
	private EntityRef<tbl_Product> _tbl_Product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCartIDChanging(int value);
    partial void OnCartIDChanged();
    partial void OnProductIDChanging(System.Nullable<int> value);
    partial void OnProductIDChanged();
    partial void OnQuantityChanging(System.Nullable<int> value);
    partial void OnQuantityChanged();
    partial void OnSessionIDChanging(string value);
    partial void OnSessionIDChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDateAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateAddedChanged();
    #endregion
	
	public tbl_ShoppingCart()
	{
		this._tbl_Product = default(EntityRef<tbl_Product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CartID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CartID
	{
		get
		{
			return this._CartID;
		}
		set
		{
			if ((this._CartID != value))
			{
				this.OnCartIDChanging(value);
				this.SendPropertyChanging();
				this._CartID = value;
				this.SendPropertyChanged("CartID");
				this.OnCartIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
	public System.Nullable<int> ProductID
	{
		get
		{
			return this._ProductID;
		}
		set
		{
			if ((this._ProductID != value))
			{
				if (this._tbl_Product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnProductIDChanging(value);
				this.SendPropertyChanging();
				this._ProductID = value;
				this.SendPropertyChanged("ProductID");
				this.OnProductIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="VarChar(20)")]
	public string SessionID
	{
		get
		{
			return this._SessionID;
		}
		set
		{
			if ((this._SessionID != value))
			{
				this.OnSessionIDChanging(value);
				this.SendPropertyChanging();
				this._SessionID = value;
				this.SendPropertyChanged("SessionID");
				this.OnSessionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="Date")]
	public System.Nullable<System.DateTime> DateAdded
	{
		get
		{
			return this._DateAdded;
		}
		set
		{
			if ((this._DateAdded != value))
			{
				this.OnDateAddedChanging(value);
				this.SendPropertyChanging();
				this._DateAdded = value;
				this.SendPropertyChanged("DateAdded");
				this.OnDateAddedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Product_tbl_ShoppingCart", Storage="_tbl_Product", ThisKey="ProductID", OtherKey="Id", IsForeignKey=true)]
	public tbl_Product tbl_Product
	{
		get
		{
			return this._tbl_Product.Entity;
		}
		set
		{
			tbl_Product previousValue = this._tbl_Product.Entity;
			if (((previousValue != value) 
						|| (this._tbl_Product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_Product.Entity = null;
					previousValue.tbl_ShoppingCarts.Remove(this);
				}
				this._tbl_Product.Entity = value;
				if ((value != null))
				{
					value.tbl_ShoppingCarts.Add(this);
					this._ProductID = value.Id;
				}
				else
				{
					this._ProductID = default(Nullable<int>);
				}
				this.SendPropertyChanged("tbl_Product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_UserProfile")]
public partial class tbl_UserProfile : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Uid;
	
	private string _firstname;
	
	private string _lastname;
	
	private string _gender;
	
	private string _state;
	
	private System.Nullable<int> _pincode;
	
	private string _deliveryaddress;
	
	private string _email;
	
	private string _mobile;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUidChanging(string value);
    partial void OnUidChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OnpincodeChanging(System.Nullable<int> value);
    partial void OnpincodeChanged();
    partial void OndeliveryaddressChanging(string value);
    partial void OndeliveryaddressChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    #endregion
	
	public tbl_UserProfile()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Uid
	{
		get
		{
			return this._Uid;
		}
		set
		{
			if ((this._Uid != value))
			{
				this.OnUidChanging(value);
				this.SendPropertyChanging();
				this._Uid = value;
				this.SendPropertyChanged("Uid");
				this.OnUidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50)")]
	public string firstname
	{
		get
		{
			return this._firstname;
		}
		set
		{
			if ((this._firstname != value))
			{
				this.OnfirstnameChanging(value);
				this.SendPropertyChanging();
				this._firstname = value;
				this.SendPropertyChanged("firstname");
				this.OnfirstnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
	public string lastname
	{
		get
		{
			return this._lastname;
		}
		set
		{
			if ((this._lastname != value))
			{
				this.OnlastnameChanging(value);
				this.SendPropertyChanging();
				this._lastname = value;
				this.SendPropertyChanged("lastname");
				this.OnlastnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(50)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
	public string state
	{
		get
		{
			return this._state;
		}
		set
		{
			if ((this._state != value))
			{
				this.OnstateChanging(value);
				this.SendPropertyChanging();
				this._state = value;
				this.SendPropertyChanged("state");
				this.OnstateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="Int")]
	public System.Nullable<int> pincode
	{
		get
		{
			return this._pincode;
		}
		set
		{
			if ((this._pincode != value))
			{
				this.OnpincodeChanging(value);
				this.SendPropertyChanging();
				this._pincode = value;
				this.SendPropertyChanged("pincode");
				this.OnpincodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliveryaddress", DbType="VarChar(50)")]
	public string deliveryaddress
	{
		get
		{
			return this._deliveryaddress;
		}
		set
		{
			if ((this._deliveryaddress != value))
			{
				this.OndeliveryaddressChanging(value);
				this.SendPropertyChanging();
				this._deliveryaddress = value;
				this.SendPropertyChanged("deliveryaddress");
				this.OndeliveryaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NChar(10)")]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class showProductResult
{
	
	private int _Id;
	
	private string _Catname;
	
	private string _desc;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private int _Id1;
	
	private string _Scatname;
	
	private string _desc1;
	
	private System.Nullable<int> _pid;
	
	private System.Nullable<System.DateTime> _dateon1;
	
	private int _Id2;
	
	private string _pname;
	
	private string _desc2;
	
	private System.Nullable<decimal> _price;
	
	private System.Nullable<int> _qty;
	
	private string _size;
	
	private string _color;
	
	private string _material;
	
	private string _imgthumb;
	
	private string _imgfront;
	
	private string _imgback;
	
	private System.Nullable<int> _pid1;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<System.DateTime> _dateon2;
	
	public showProductResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catname", DbType="VarChar(50)")]
	public string Catname
	{
		get
		{
			return this._Catname;
		}
		set
		{
			if ((this._Catname != value))
			{
				this._Catname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(50)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this._desc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this._dateon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int NOT NULL")]
	public int Id1
	{
		get
		{
			return this._Id1;
		}
		set
		{
			if ((this._Id1 != value))
			{
				this._Id1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scatname", DbType="VarChar(50)")]
	public string Scatname
	{
		get
		{
			return this._Scatname;
		}
		set
		{
			if ((this._Scatname != value))
			{
				this._Scatname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc1", DbType="VarChar(50)")]
	public string desc1
	{
		get
		{
			return this._desc1;
		}
		set
		{
			if ((this._desc1 != value))
			{
				this._desc1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
	public System.Nullable<int> pid
	{
		get
		{
			return this._pid;
		}
		set
		{
			if ((this._pid != value))
			{
				this._pid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon1", DbType="Date")]
	public System.Nullable<System.DateTime> dateon1
	{
		get
		{
			return this._dateon1;
		}
		set
		{
			if ((this._dateon1 != value))
			{
				this._dateon1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id2", DbType="Int NOT NULL")]
	public int Id2
	{
		get
		{
			return this._Id2;
		}
		set
		{
			if ((this._Id2 != value))
			{
				this._Id2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="VarChar(50)")]
	public string pname
	{
		get
		{
			return this._pname;
		}
		set
		{
			if ((this._pname != value))
			{
				this._pname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc2", DbType="VarChar(150)")]
	public string desc2
	{
		get
		{
			return this._desc2;
		}
		set
		{
			if ((this._desc2 != value))
			{
				this._desc2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
	public System.Nullable<int> qty
	{
		get
		{
			return this._qty;
		}
		set
		{
			if ((this._qty != value))
			{
				this._qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(50)")]
	public string size
	{
		get
		{
			return this._size;
		}
		set
		{
			if ((this._size != value))
			{
				this._size = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this._color = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="VarChar(50)")]
	public string material
	{
		get
		{
			return this._material;
		}
		set
		{
			if ((this._material != value))
			{
				this._material = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgthumb", DbType="VarChar(50)")]
	public string imgthumb
	{
		get
		{
			return this._imgthumb;
		}
		set
		{
			if ((this._imgthumb != value))
			{
				this._imgthumb = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgfront", DbType="VarChar(50)")]
	public string imgfront
	{
		get
		{
			return this._imgfront;
		}
		set
		{
			if ((this._imgfront != value))
			{
				this._imgfront = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgback", DbType="VarChar(50)")]
	public string imgback
	{
		get
		{
			return this._imgback;
		}
		set
		{
			if ((this._imgback != value))
			{
				this._imgback = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid1", DbType="Int")]
	public System.Nullable<int> pid1
	{
		get
		{
			return this._pid1;
		}
		set
		{
			if ((this._pid1 != value))
			{
				this._pid1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this._sid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon2", DbType="Date")]
	public System.Nullable<System.DateTime> dateon2
	{
		get
		{
			return this._dateon2;
		}
		set
		{
			if ((this._dateon2 != value))
			{
				this._dateon2 = value;
			}
		}
	}
}

public partial class product_listResult
{
	
	private int _Id;
	
	private string _Catname;
	
	private string _desc;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private int _Id1;
	
	private string _Scatname;
	
	private string _desc1;
	
	private System.Nullable<int> _pid;
	
	private System.Nullable<System.DateTime> _dateon1;
	
	private int _Id2;
	
	private string _pname;
	
	private string _desc2;
	
	private System.Nullable<decimal> _price;
	
	private System.Nullable<int> _qty;
	
	private string _size;
	
	private string _color;
	
	private string _material;
	
	private string _imgthumb;
	
	private string _imgfront;
	
	private string _imgback;
	
	private System.Nullable<int> _pid1;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<System.DateTime> _dateon2;
	
	public product_listResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catname", DbType="VarChar(50)")]
	public string Catname
	{
		get
		{
			return this._Catname;
		}
		set
		{
			if ((this._Catname != value))
			{
				this._Catname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(50)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this._desc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this._dateon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int NOT NULL")]
	public int Id1
	{
		get
		{
			return this._Id1;
		}
		set
		{
			if ((this._Id1 != value))
			{
				this._Id1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scatname", DbType="VarChar(50)")]
	public string Scatname
	{
		get
		{
			return this._Scatname;
		}
		set
		{
			if ((this._Scatname != value))
			{
				this._Scatname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc1", DbType="VarChar(50)")]
	public string desc1
	{
		get
		{
			return this._desc1;
		}
		set
		{
			if ((this._desc1 != value))
			{
				this._desc1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
	public System.Nullable<int> pid
	{
		get
		{
			return this._pid;
		}
		set
		{
			if ((this._pid != value))
			{
				this._pid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon1", DbType="Date")]
	public System.Nullable<System.DateTime> dateon1
	{
		get
		{
			return this._dateon1;
		}
		set
		{
			if ((this._dateon1 != value))
			{
				this._dateon1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id2", DbType="Int NOT NULL")]
	public int Id2
	{
		get
		{
			return this._Id2;
		}
		set
		{
			if ((this._Id2 != value))
			{
				this._Id2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="VarChar(50)")]
	public string pname
	{
		get
		{
			return this._pname;
		}
		set
		{
			if ((this._pname != value))
			{
				this._pname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc2", DbType="VarChar(150)")]
	public string desc2
	{
		get
		{
			return this._desc2;
		}
		set
		{
			if ((this._desc2 != value))
			{
				this._desc2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
	public System.Nullable<int> qty
	{
		get
		{
			return this._qty;
		}
		set
		{
			if ((this._qty != value))
			{
				this._qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(50)")]
	public string size
	{
		get
		{
			return this._size;
		}
		set
		{
			if ((this._size != value))
			{
				this._size = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this._color = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="VarChar(50)")]
	public string material
	{
		get
		{
			return this._material;
		}
		set
		{
			if ((this._material != value))
			{
				this._material = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgthumb", DbType="VarChar(50)")]
	public string imgthumb
	{
		get
		{
			return this._imgthumb;
		}
		set
		{
			if ((this._imgthumb != value))
			{
				this._imgthumb = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgfront", DbType="VarChar(50)")]
	public string imgfront
	{
		get
		{
			return this._imgfront;
		}
		set
		{
			if ((this._imgfront != value))
			{
				this._imgfront = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgback", DbType="VarChar(50)")]
	public string imgback
	{
		get
		{
			return this._imgback;
		}
		set
		{
			if ((this._imgback != value))
			{
				this._imgback = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid1", DbType="Int")]
	public System.Nullable<int> pid1
	{
		get
		{
			return this._pid1;
		}
		set
		{
			if ((this._pid1 != value))
			{
				this._pid1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this._sid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon2", DbType="Date")]
	public System.Nullable<System.DateTime> dateon2
	{
		get
		{
			return this._dateon2;
		}
		set
		{
			if ((this._dateon2 != value))
			{
				this._dateon2 = value;
			}
		}
	}
}

public partial class Shop_Cart_ViewResult
{
	
	private int _Id;
	
	private string _pname;
	
	private string _desc;
	
	private System.Nullable<decimal> _price;
	
	private System.Nullable<int> _qty;
	
	private string _size;
	
	private string _color;
	
	private string _material;
	
	private string _imgthumb;
	
	private string _imgfront;
	
	private string _imgback;
	
	private System.Nullable<int> _pid;
	
	private System.Nullable<int> _sid;
	
	private System.Nullable<System.DateTime> _dateon;
	
	private int _CartID;
	
	private System.Nullable<int> _ProductID;
	
	private System.Nullable<int> _Quantity;
	
	private string _SessionID;
	
	private System.Nullable<decimal> _Price1;
	
	private System.Nullable<System.DateTime> _DateAdded;
	
	public Shop_Cart_ViewResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="VarChar(50)")]
	public string pname
	{
		get
		{
			return this._pname;
		}
		set
		{
			if ((this._pname != value))
			{
				this._pname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[desc]", Storage="_desc", DbType="VarChar(150)")]
	public string desc
	{
		get
		{
			return this._desc;
		}
		set
		{
			if ((this._desc != value))
			{
				this._desc = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this._price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Int")]
	public System.Nullable<int> qty
	{
		get
		{
			return this._qty;
		}
		set
		{
			if ((this._qty != value))
			{
				this._qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(50)")]
	public string size
	{
		get
		{
			return this._size;
		}
		set
		{
			if ((this._size != value))
			{
				this._size = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(50)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this._color = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="VarChar(50)")]
	public string material
	{
		get
		{
			return this._material;
		}
		set
		{
			if ((this._material != value))
			{
				this._material = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgthumb", DbType="VarChar(50)")]
	public string imgthumb
	{
		get
		{
			return this._imgthumb;
		}
		set
		{
			if ((this._imgthumb != value))
			{
				this._imgthumb = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgfront", DbType="VarChar(50)")]
	public string imgfront
	{
		get
		{
			return this._imgfront;
		}
		set
		{
			if ((this._imgfront != value))
			{
				this._imgfront = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgback", DbType="VarChar(50)")]
	public string imgback
	{
		get
		{
			return this._imgback;
		}
		set
		{
			if ((this._imgback != value))
			{
				this._imgback = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
	public System.Nullable<int> pid
	{
		get
		{
			return this._pid;
		}
		set
		{
			if ((this._pid != value))
			{
				this._pid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sid", DbType="Int")]
	public System.Nullable<int> sid
	{
		get
		{
			return this._sid;
		}
		set
		{
			if ((this._sid != value))
			{
				this._sid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateon", DbType="Date")]
	public System.Nullable<System.DateTime> dateon
	{
		get
		{
			return this._dateon;
		}
		set
		{
			if ((this._dateon != value))
			{
				this._dateon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CartID", DbType="Int NOT NULL")]
	public int CartID
	{
		get
		{
			return this._CartID;
		}
		set
		{
			if ((this._CartID != value))
			{
				this._CartID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int")]
	public System.Nullable<int> ProductID
	{
		get
		{
			return this._ProductID;
		}
		set
		{
			if ((this._ProductID != value))
			{
				this._ProductID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
	public System.Nullable<int> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this._Quantity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="VarChar(20)")]
	public string SessionID
	{
		get
		{
			return this._SessionID;
		}
		set
		{
			if ((this._SessionID != value))
			{
				this._SessionID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price1", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Price1
	{
		get
		{
			return this._Price1;
		}
		set
		{
			if ((this._Price1 != value))
			{
				this._Price1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="Date")]
	public System.Nullable<System.DateTime> DateAdded
	{
		get
		{
			return this._DateAdded;
		}
		set
		{
			if ((this._DateAdded != value))
			{
				this._DateAdded = value;
			}
		}
	}
}
#pragma warning restore 1591
